# Generated by Django 4.1 on 2022-08-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cards')),
                ('meaning', models.TextField(max_length=2000)),
                ('reversed_meaning', models.TextField(max_length=2000)),
            ],
        ),
    ]
