# Generated by Django 4.1 on 2022-08-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_tarotcard_card_number_pastpresentfuture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcard',
            name='card_number',
        ),
    ]
