# Generated by Django 4.1 on 2022-08-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_remove_tarotcard_card_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pastPresentFuture',
        ),
    ]
